query ($page: Int, $perPage: Int, $search: String, $genre: String) {
  Page(page: $page, perPage: $perPage) {
    pageInfo {
      total
      perPage
    }
    media(search: $search, type: ANIME, sort: POPULARITY_DESC, genre: $genre) {
      id
      title {
        romaji
      }
      format
      genres
      coverImage {
        extraLarge
        large
        medium
        color
      }
      episodes
      averageScore
      status
      season
      seasonYear
      popularity
      duration
    }
  }
}
