query ($id: Int) {
    Media(id: $id) {
        id
        relations {
            edges {
                node {
                    id
                    coverImage {
                        large
                    }
                    title{
                        romaji
                    }
                    format
                    status
                }
                relationType
            }
        }
        characters(sort: ROLE) {
            edges {
                id
                node {
                    image {
                        large
                        medium
                    }
                    name {
                        full
                    }
                }
                voiceActors(language: JAPANESE) {
                    id
                    name {
                        full
                    }
                    languageV2
                    image {
                        large
                        medium
                    }
                }
                role
            }
        }
        staff {
            edges {
                id
                role
                node {
                    name {
                        full
                    }
                    image {
                        large
                        medium
                    }
                }
            }
        }
    }
}