query ($page: Int, $perPage: Int, $search: String, $year: Int) {
  Page(page: $page, perPage: $perPage) {
    pageInfo {
      total
      perPage
    }
    media(search: $search, type: ANIME, sort: POPULARITY_DESC, seasonYear: $year, season: SUMMER) {
      id
      title {
        romaji
      }
      format
      genres
      coverImage {
        extraLarge
        large
        medium
        color
      }
      studios {
        nodes {
          name
          isAnimationStudio
        }
      }
      episodes
      averageScore
    }
  }
}
